language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    dist: bionic
    sudo: required
    install: "./travis-install.sh"
    script: make test
  - &osx_build
    os: osx
    compiler: clang
    install: "./travis-install.sh"
    script: make xcode/test
    before_deploy:
    - make xcode/dist
    - |
      zip -r ${RIME_VARIANT:-rime}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip \
      dist thirdparty/bin thirdparty/share \
      -x '*/curl.exe'
    deploy:
      provider: releases
      api_key:
        secure: Le2PfdrOqVmk5c1Eu/q9fvLGG1WZz5SuIXw0LVTqWn8cPCJvvsh9/RsjKx59uI0rxs/sJnbsCnPSaiveY5i51Jy7apkqtysUfglr+2CjgyXY5s7qBWiZ60/j2V5CDkk+Q/PSB/GXcVxHQWPh6X1M75GWa9b+4COKJX3Kh/FO0rM=
      file: "${RIME_VARIANT:-rime}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip"
      skip_cleanup: true
      name: librime ${TRAVIS_TAG}
      body: 'chore(release): ${TRAVIS_TAG} :tada:'
      draft: true
      on:
        repo: rime/librime
        tags: true
  - <<: *osx_build
    if: tag IS present
    env: RIME_PLUGINS="${RIME_BUNDLED_PLUGINS}" RIME_VARIANT="rime-with-plugins"
